name: Run e2e tests
on: workflow_dispatch
jobs:
  playwright:
    name: Run Playwright tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Lemmy server
        run: USER_ID="$(id -u)" GROUP_ID="$(id -g)" docker compose -f e2e/ci/docker-compose.yml up -d
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build project
        run: pnpm build
        env:
          VITE_FORCE_LEMMY_INSECURE: 1
          VITE_CUSTOM_LEMMY_SERVERS: localhost:8536
      - name: Install Playwright dependencies
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
