name: Run e2e tests
on: workflow_dispatch
jobs:
  playwright:
    name: Run Playwright tests
    runs-on: ubuntu-latest
    # services:
    #   postgres:
    #     image: postgres
    #     ports:
    #       - 5432:5432
    #     env:
    #       POSTGRES_USER: lemmy
    #       POSTGRES_PASSWORD: password
    #       POSTGRES_DB: lemmy
    steps:
      - uses: actions/checkout@v4
      # - name: Start Lemmy server
      #   run: USER_ID="$(id -u)" GROUP_ID="$(id -g)" docker compose -f e2e/ci/docker-compose.yml up -d
      # - uses: moonrepo/setup-rust@v1
      # - name: Fetch lemmy
      #   run: |
      #     git clone https://github.com/lemmynet/lemmy
      #     cd lemmy
      #     cargo run --bin lemmy_server --release &
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      # - name: Check if lemmy is running
      #   run: |
      #     echo "LOG --> Checking 127.0.0.1..."
      #     curl -v http://127.0.0.1:8536
      #     echo "LOG --> Checking localhost..."
      #     curl -v http://localhost:8536
      # echo "LOG --> Look for LISTENing ports"
      # sudo lsof -i -P -n | grep LISTEN
      - name: Build project
        run: pnpm build
        env:
          VITE_FORCE_LEMMY_INSECURE: 1
          VITE_CUSTOM_LEMMY_SERVERS: localhost:8536
      - name: Install Playwright dependencies
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          # sh e2e/ci/launch_lemmy.sh
          run: USER_ID="$(id -u)" GROUP_ID="$(id -g)" docker compose -f e2e/ci/docker-compose.yml up -d
          pnpm run test:e2e
      # - uses: actions/upload-artifact@v4
      #   if: ${{ !cancelled() }}
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 7
