name: Run e2e tests
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
  push:
    branches:
      - update-e2e-action
  pull_request:
    branches:
      - update-e2e-action
jobs:
  playwright:
    name: Run Playwright tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Lemmy server
        run: USER_ID="$(id -u)" GROUP_ID="$(id -g)" docker compose -f e2e/ci/docker-compose.yml up -d
      - name: Start Caddy
        run: sudo e2e/ci/bin/caddy start --config e2e/ci/Caddyfile
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build project
        run: pnpm build
      - name: Install Playwright dependencies
        run: npx playwright install --with-deps
      - name: Run tests
        run: pnpm run test:e2e
